name: eo-crops
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - cartopy=0.21.0
  - libgdal=3.6.0
  - gdal=3.6.0
  - pandoc
  - pip :
      - -r requirements.txt
      - -r requirements-doc.txt
      #- git+https://github.com/WFP-VAM/modape if you want to apply whitakker smoothing


